M48
; DRILL file {KiCad (6.0.0)} date Thu Jan 12 11:24:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-12T11:24:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0472
%
G90
G05
T1
X5.35Y-2.5
X5.65Y-2.5
X5.75Y-2.5
X6.05Y-2.5
T2
X5.25Y-2.35
X5.3Y-2.35
X5.35Y-2.35
T3
X5.35Y-2.6
X5.35Y-2.7
X5.35Y-3.0
X5.55Y-2.6
X5.55Y-2.7
X5.55Y-3.0
T4
X5.2Y-2.6
X5.2Y-3.0
X5.7Y-2.7
X5.7Y-2.8
X5.7Y-2.9
T5
X5.6122Y-2.325
X5.75Y-2.325
X5.8878Y-2.325
X6.0Y-2.6744
X6.0Y-2.8122
X6.0Y-2.95
X6.0256Y-2.325
T0
M30
